HOTFIX 2: Remove remaining commit message from line 1318
Fixed build error on line 1318.

The previous hotfix removed most of the commit message text,
but line 1318 still had "Fixes: Priority URL Queue now actually processes the URLs!"

This was causing:
ERROR: Expected ";" but found "URL"

Changed line 1318 from:
Fixes: Priority URL Queue now actually processes the URLs! (page.isPriorityUrl) {

To:
if (page.isPriorityUrl) {

This should finally fix the build.